# Generated by Django 4.1.2 on 2022-10-07 10:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Film',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(null=True, upload_to='film')),
                ('title', models.CharField(max_length=100, verbose_name='Заголовок')),
                ('link', models.URLField(verbose_name='Ссылка')),
                ('producer', models.TextField(null=True, verbose_name='Режиссер')),
                ('rating', models.FloatField(default=0, verbose_name='Рейтинг')),
                ('duration', models.DurationField(null=True, verbose_name='Длительность')),
            ],
            options={
                'verbose_name': 'фильм',
                'verbose_name_plural': 'фильмы',
            },
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('text', models.TextField(verbose_name='Текст')),
                ('id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('film', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.film', verbose_name='Название фильма')),
            ],
            options={
                'verbose_name': 'отзыв',
                'verbose_name_plural': 'отзывы',
            },
        ),
    ]
